export const section: string; 
export const shape_bottom: string;
export const shape: string;
export const container: string;
export const bio: string;
export const picture: string;
export const slogan: string; 
export const emphasis: string;
export const pitch: string;
