name: Deploy to dev

on: 
  push: 
    branches:
      - development
      - github_worflow_fired_and_failed

env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  Build_with_SSH:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn build

    - name: Copy files via scp
      uses: appleboy/scp-action@master              
      with:
        host: ${{ secrets.HOST_SERVER }}
        key: ${{ secrets.TCIMPIDIS_PUB }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "./build"
        target: ${{ secrets.DEV_WEB_SERVER_LOCATION }}