name: Deploy to dev

on: 
  push: 
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' 
    steps:
      - name: Deploying to Digitalocean droplet
        uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.SERVER_ADMIN }}
          password: ${{ secrets.SERVER_ADMIN_PW }}
          script: |
            cd ${{ secrets.DEV_WEB_SERVER_LOCATION }} # we move into our app's folder
            git pull # we pull any changes from git
            npm prune # we remove any unused dependencies
            npm install # we install any missing dependencies
            npm run build # we build our app
            pm2 reload all # we reload the app via PM2