name: Deploy to dev

on: 
  push: 
    branches:
      - development
      - github_worflow_fired_and_failed

jobs:
  Build_with_SSH:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn build

    - name: Copy files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}    
        source: "./build/."
        target: $${{ secrets.DEV_WEB_SERVER_LOCATION }}
        strip_components: 1