name: Deploy to dev

on: 
  push: 
    branches:
      - development
      - wrong_file_name_on_build

jobs:
  Build_with_SSH:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn build

    - name: Clean old directory
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.SERVER_ADMIN }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}    
        script: rm -r ${{ secrets.DEV_WEB_SERVER_LOCATION }}/*

    - name: Copy files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.SERVER_ADMIN }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}    
        source: "out/"
        target: ${{ secrets.DEV_WEB_SERVER_LOCATION }}
        strip_components: 1