name: Deploy to dev

on: 
  push: 
    branches:
      - development
      - new_branch_has_to_be_lower_case

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tcimpidis/dev/portfilio

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          build-args: |
            NEXT_PUBLIC_NODE_ENV=development
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy package to Server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.SERVER_ADMIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            echo $GITHUB_TOKEN | docker login ${{ env.REGISTRY }} -u $GITHUB_USERNAME --password-stdin
            docker pull ${{ steps.meta.outputs.tags }}:latest
            docker stop ${{ env.IMAGE_NAME }}
            docker system prune -f
            docker run --name ${{ env.IMAGE_NAME }} -dit -p 3000:3000 ${{ steps.meta.outputs.tags }}:latest